### ISSUE TITLE
Java Enum

### ISSUE THREAD

**Issue by Nbsaw** [Nbsaw/notes#21]
Java 1.5 提供了**枚举类型**。枚举类型(enum type)是指由一组固定的常量组成合法值的类型。例如一年中的季节，太阳系中的行星或者一副牌中的花色。在编程语言还没有引入枚举之前。通常都是用int常量来代表每一个成员:

``` java
// The int enum pattern - severely deficient!
public static final int APPLE_FUJI         = 0;
public static final int APPLE_PIPPIN       = 1;
public static final int APPLE_GRANNY_SMITH = 2;

public static final int ORANGE_NAVEL  = 0;
public static final int ORANGE_TEMPLE = 1;
public static final int ORANGE_BLOOD  = 2;
```

这种写法叫做`int枚举模式`。存在很多不足。它在类型安全性和使用性上没有任何帮助。如果你将apple闯到想要orange的方法里也是可以的。并且编译器不会出现警告。然后还会用`==`来判断他们是否相等。甚至你还可以让它们相加减乘除 = =

``` java
// Tasty citrus flavored applesauce
int i = (APPLE_FUJI - ORANGE_TEMPKLE) / APPLE_PIPPIN;
```

因为没有给int提供命名空间。所以都是在前面加前缀避免冲突。

采用int枚举模式的程序是非常脆弱的。因为int枚举是编译常量。被编译到它们的客户端里。如果与枚举常量关联的int发生了变化。客户端就必须重新编译。如果没有重新编译，程序还是可以运行的，但是它们的行为就不确定了。

将int枚举常量翻译成可打印的字符串并没有便利的办法。如果你直接把变量打印出来你只能看到个数字。并没有什么卵用。除此之外你还不能获取这一组枚举常量的大小(总数)。也无法遍历这一组枚举常量。

**Comment by Nbsaw** [comment]
然后你想到用字符串来表示不就可以打印出语义清晰字符串了吗，岂不美滋滋。是的确实可以。这个模式叫做`String枚举模式`但是它也有很多类型的缺点。它也不能遍历也不能获取总的大小。并且如果进行字符串的比较操作其实是很费时间的。性能不好。还有就是一些人(初级开发人员)写代码直接硬编码然后比较。而不是拿枚举变量进行比较。这时候如果书写错位(打错字)那就gg。并且这个错误不会被抛出也无法检测到。你可以想象一下如果有一个switch语句。如果你有很多个字符串变量。如果你打错了比较的条件比如`Asse`打成了`Ases`。并且你有一个默认的执行。那么`Asse`这个case就永远无法被执行到。会默认跳到default那边去。

**Comment by Nbsaw** [comment]
幸运的是,Java1.5以后就提出了一种替代的解决方案。可以避免int和String枚举模式的缺点。并提供许多额外的好处。这就是JLD,8.9。下面以最简单的形式演示这种模式:

``` java
public enum Apple   { FUJI  , PIPPIN , GRANNY_SMITH }
public enum Orange  { NAVEL , TAMPLE , BLOOD }
```

**Comment by GWELL52** [comment]
可以 APPLE_FUJI(0), APPLE_PIPPIN(1), APPLE_GRANNY_SMITH(2)

**Comment by Nbsaw** [comment]
为什么需要枚举方法?这是因为这是个很方便的玩意。比如太阳系中有8颗行星。每颗行星都有自己的质量和半径。通过这两个属性可以计算出行星的重力。下面就是这个枚举。每个枚举常量后面括号中的数值就是传给构造器的参数。在这里，用到的参数就是质量和半径:

``` java

```

**Comment by Nbsaw** [comment]
枚举是可以遍历的使用`values()`。如果我们要算一个物体在地球以外的星球的重力可以像下面这样写。
``` java
public class WeightTable {
    public static void main(String[] args) {
        double earthWeight = 175.00;
        double mass = earthWeight / Planet.EARTH.surfaceGravity();
        for (Planet planet : Planet.values())
            System.out.printf("Weight on %s is %f%n", planet, planet.surfaceWeight(mass));
    }
}
```

**Comment by Nbsaw** [comment]
Planet示例中所示的方法对于绝大多数枚举类型来说就足够了。但是对于行为不一样的枚举来说用上面那种办法行不通。

**Comment by Nbsaw** [comment]
那么有办法可以做到避免这种状况吗。当然有。就是用抽象类。

``` java
public enum  Operation {
    PLUS {
        @Override
        double apply(double x, double y) {
            return x + y;
        }
    }, MINUS {
        @Override
        double apply(double x, double y) {
            return x - y;
        }
    }, TIMES {
        @Override
        double apply(double x, double y) {
            return x * y;
        }
    }, DIVIDE {
        @Override
        double apply(double x, double y) {
            return x / y;
        }
    };

    abstract double apply(double x,double y);
}
```

这样子就不会有忘记的情况了。因为你忘了编译都无法通过。

**Comment by Nbsaw** [comment]
给枚举类型添加`toString`方法是有必要的因为这很有用。

``` java
public enum  Operation {
    PLUS("+") {
        @Override
        double apply(double x, double y) {
            return x + y;
        }
    },
    MINUS("-") {
        @Override
        double apply(double x, double y) {
            return x - y;
        }
    },
    TIMES("*") {
        @Override
        double apply(double x, double y) {
            return x * y;
        }
    },
    DIVIDE("/") {
        @Override
        double apply(double x, double y) {
            return x / y;
        }
    };

    private final String symbol;
    Operation(String symbol){ this.symbol = symbol; }
    @Override public String toString() { return symbol; }
    abstract double apply(double x, double y);
}
```

**Comment by Nbsaw** [comment]
用抽象类的办法虽然好但也有美中不足的地方。因为很难共享代码了。如果你要共享代码那就不要这么写。例如,考虑用一个枚举表示薪资包中的工作天数。这个枚举有一个方法，根据给定某工人的基本工资(按小时)以及当天的工作时间，来计算它当天的薪酬。在五个工作日中。超过八个小时都会给额外的加班工资。在双休日中。所有工作都会有额外的加班工资。利用switch语句可以很简单的实现这个过程。这个例子用了dobule作为工资的变量类型。实际上不要用dobule，这里只是为了讲解这个例子才用的。

**Comment by Nbsaw** [comment]
幸运的是有一种设计模式可以解决这个问题。这个模式叫做**"策略枚举(strategy enum)"**。

**Comment by Nbsaw** [comment]
说完上面那些说一点要注意的事情

**Comment by Nbsaw** [comment]
上面说的基本用法说的差不多了。说一个继承的问题。枚举是不允许继承的因为前面说了它是真正final的类。这也意味着它无法被继承修改。那么如果想继承的话应该怎么办呢。其实也很简单只要定义好接口，我们就可以实现枚举的继承。实现可以伸缩的枚举。

**Comment by Nbsaw** [comment]
基本用法说完了。说下要注意的一些东西。

1. 不要使用`ordinal`方法。不可靠。

2. 最好使用EnumMap来存特地的枚举常量。而不是数组。

3. 最好用EnumSet来存枚举常量。

**Comment by Nbsaw** [comment]
以上。
