### ISSUE TITLE
自动装箱的一点小坑

### ISSUE THREAD

**Issue by Nbsaw** [Nbsaw/notes#26]
首先要知道Java的类型系统有两部分组成。

一种是基本(primitive)类型,如int,double,boolean等。另一种是引用类型(reference type),如String,List那些。基本类型对应的装箱类型叫做**装箱基本类型(boxed primitive)**。

原始类型最明显的地方就是不能用`.`操作符。因为它们并不继承自`Object`。并不是对象。有一点要提的是泛型只支持引用类型不支持原始类型。也就是说你在`<>`里要写`装箱基本类型`。

**Comment by Nbsaw** [comment]
原始类型。你喜欢怎么比较都可以 。 它们都是相等的。但是包装类型不可以。下面这段代码如果你用`==`判断就是`false`。

``` java
Long s = 128L;
Long b = 128L;
System.out.println(s == b);
```

但是也并不是所有数字都是这个结果。这玩意也有等于`true`的情况。那就是数字在`-128-127`的情况下。这时候的比较都是相等的。至于为什么这样。。我并不知道。。不过这个数字应该看起来就是那个吧 。。。 8位二进制数。

**Comment by Nbsaw** [comment]
装箱类型还支持传null参数这就很棒(La ji)了。

考虑下面这段代码

**Comment by Nbsaw** [comment]
![image](https://user-images.githubusercontent.com/12481935/30323152-ac70574e-97ee-11e7-8fd3-5fa89d3863d4.png)
接下来这个缺点是最骚的。

**Comment by Nbsaw** [comment]
说以批判了一番以后的结论就是能不用装修就别用。只有该用的地方才用比如使用泛型的时候。

**Comment by vipcchua** [comment]
哦豁
